/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.Home;

import my.FullPatientHistory.FullPatientHistory;
import javax.swing.JOptionPane;
import my.AddNewPatientRecord.AddNewPatientRecord;
import my.LoginUi.Login;
import my.AddDiagnosisInformation.AddDiagnosisInformation;
import my.HospitalInformation.HospitalInformation;
import my.UpdatePatient.UpdatePatientRecord;

/**
 *
 * @author shane
 */
public class Home extends javax.swing.JFrame {

    public int I = 0;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TwoArrow = new javax.swing.JButton();
        AddPatientRecord = new javax.swing.JButton();
        AddPatientDiagnosis = new javax.swing.JButton();
        PatientHistory = new javax.swing.JButton();
        UpdatePatientRecord = new javax.swing.JButton();
        HospitalInformation = new javax.swing.JButton();
        LogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TwoArrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Images/two arrow.png"))); // NOI18N
        TwoArrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoArrowActionPerformed(evt);
            }
        });
        getContentPane().add(TwoArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        AddPatientRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Images/add new patient.png"))); // NOI18N
        AddPatientRecord.setText("Add New Patient Record");
        AddPatientRecord.setPreferredSize(new java.awt.Dimension(240, 59));
        AddPatientRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPatientRecordActionPerformed(evt);
            }
        });
        getContentPane().add(AddPatientRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        AddPatientDiagnosis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Images/add diag.png"))); // NOI18N
        AddPatientDiagnosis.setText("Add Patient Diagnosis");
        AddPatientDiagnosis.setPreferredSize(new java.awt.Dimension(240, 59));
        AddPatientDiagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPatientDiagnosisActionPerformed(evt);
            }
        });
        getContentPane().add(AddPatientDiagnosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        PatientHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Images/rsz_history1.png"))); // NOI18N
        PatientHistory.setText("Patient History");
        PatientHistory.setPreferredSize(new java.awt.Dimension(240, 59));
        PatientHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientHistoryActionPerformed(evt);
            }
        });
        getContentPane().add(PatientHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        UpdatePatientRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Images/rsz_update_details.png"))); // NOI18N
        UpdatePatientRecord.setText("Update Patient Record");
        UpdatePatientRecord.setPreferredSize(new java.awt.Dimension(240, 59));
        UpdatePatientRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePatientRecordActionPerformed(evt);
            }
        });
        getContentPane().add(UpdatePatientRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        HospitalInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Images/rsz_hospital_information.png"))); // NOI18N
        HospitalInformation.setText("Hospital Information");
        HospitalInformation.setPreferredSize(new java.awt.Dimension(240, 59));
        HospitalInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalInformationActionPerformed(evt);
            }
        });
        getContentPane().add(HospitalInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Images/exit.png"))); // NOI18N
        LogOut.setText("Log Out");
        LogOut.setPreferredSize(new java.awt.Dimension(240, 59));
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        getContentPane().add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Images/loginchange.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Select", JOptionPane.YES_NO_OPTION);
        
        if(a == 0){
            
            setVisible(false);
            new Login().setVisible(true);
            
        }
        
    }//GEN-LAST:event_LogOutActionPerformed

    private void TwoArrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoArrowActionPerformed
        // TODO add your handling code here:
        if(I==0){
            
            
            AddPatientRecord.setLocation(90, 30);
            AddPatientDiagnosis.setLocation(333, 30);
            PatientHistory.setLocation(576, 30);
            UpdatePatientRecord.setLocation(819, 30);
            HospitalInformation.setLocation(1062, 30);
            LogOut.setLocation(1062, 89);
            
            I=1;
            
        }else {
            
            AddPatientRecord.setLocation(10, 107);
            AddPatientDiagnosis.setLocation(10, 184);
            PatientHistory.setLocation(10, 261);
            UpdatePatientRecord.setLocation(10, 338);
            HospitalInformation.setLocation(10, 415);
            LogOut.setLocation(10, 490);
            
            I=0;
            
        }
            
        
    }//GEN-LAST:event_TwoArrowActionPerformed

    private void AddPatientRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPatientRecordActionPerformed
        // TODO add your handling code here:
        
        //setVisible(false);
        new AddNewPatientRecord().setVisible(true);
        
    }//GEN-LAST:event_AddPatientRecordActionPerformed

    private void AddPatientDiagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPatientDiagnosisActionPerformed
        // TODO add your handling code here:
        
        new AddDiagnosisInformation().setVisible(true);
        
    }//GEN-LAST:event_AddPatientDiagnosisActionPerformed

    private void PatientHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientHistoryActionPerformed
        // TODO add your handling code here:
        
        new FullPatientHistory().setVisible(true);
        
    }//GEN-LAST:event_PatientHistoryActionPerformed

    private void HospitalInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalInformationActionPerformed
        // TODO add your handling code here:
        
        new HospitalInformation().setVisible(true);
        
    }//GEN-LAST:event_HospitalInformationActionPerformed

    private void UpdatePatientRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePatientRecordActionPerformed
        // TODO add your handling code here:
        
        new UpdatePatientRecord().setVisible(true);
        
    }//GEN-LAST:event_UpdatePatientRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPatientDiagnosis;
    private javax.swing.JButton AddPatientRecord;
    private javax.swing.JButton HospitalInformation;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton PatientHistory;
    private javax.swing.JButton TwoArrow;
    private javax.swing.JButton UpdatePatientRecord;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
